# Generated by Django 5.2.4 on 2025-08-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField(default=0)),
                ('change_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_log_entry',
            },
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
