# Generated by Django 5.2.4 on 2025-08-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userlog_action_alter_userlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('update', 'Update'), ('delete', 'Delete'), ('get_all_courses', 'Get All Courses')], max_length=255),
        ),
    ]
