# Generated by Django 5.2.5 on 2025-08-27 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reminder_time', models.DateTimeField()),
                ('type', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('participants', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
