# Generated by Django 5.2.4 on 2025-10-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
