# Generated by Django 5.2.4 on 2025-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.FloatField(default=8.0),
            preserve_default=False,
        ),
    ]
