# Generated by Django 5.1 on 2025-08-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
