# Generated by Django 5.2.4 on 2025-10-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_weeklystatustask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystatustask',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklystatustask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weeklystatustask',
            name='duration',
            field=models.CharField(default='2h', max_length=20),
        ),
    ]
