# Generated by Django 5.2.4 on 2025-08-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='priiority',
            new_name='priority',
        ),
    ]
