# Generated by Django 5.2.4 on 2025-08-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_priiority_assignment_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
