# Generated by Django 5.2.4 on 2025-10-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('authorRole', models.CharField(max_length=150)),
                ('publishDate', models.DateField()),
                ('readTime', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('excerpt', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
