# Generated by Django 5.2.4 on 2025-10-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('format', models.CharField(default='live', max_length=50)),
                ('students', models.IntegerField()),
                ('maxStudents', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('topics', models.JSONField()),
                ('level', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OnDemandClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('totalHours', models.CharField(max_length=50)),
                ('format', models.CharField(default='on-demand', max_length=50)),
                ('students', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('topics', models.JSONField()),
                ('level', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('completion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('speakers', models.JSONField()),
                ('price', models.CharField(max_length=50)),
                ('attendees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.faqcategory')),
            ],
        ),
    ]
