# Generated by Django 5.2.4 on 2025-08-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
                ('instructor_avatar', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('participants', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('course_title', models.CharField(max_length=200)),
                ('topics', models.JSONField(default=list)),
                ('is_recorded', models.BooleanField(default=False)),
                ('has_handouts', models.BooleanField(default=False)),
                ('difficulty', models.CharField(max_length=200)),
                ('meeting_list', models.JSONField()),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('recording_url', models.URLField()),
                ('is_live', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.meeting')),
            ],
        ),
    ]
