# Generated by Django 5.2.4 on 2025-08-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ratings',
            field=models.IntegerField(default=4.5),
            preserve_default=False,
        ),
    ]
