# Generated by Django 5.2.4 on 2025-09-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_lms', '0003_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='ratings',
        ),
    ]
